Controllers/ContactController.cs
using ContactManagement.DAL.Comments;
using ContactManagement.DAL.Contacts;
using ContactManagement.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ContactManagement.Controllers
{
    public class ContactController : Controller
    {
        private readonly ICommentRepository _commentRepository;
        private readonly IContactRepository _contactRepository;
        private readonly string _errorMsg = "L'opération a échoué, veuillez consulter les raisons sur votre page !";

        public ContactController()
        {
            _commentRepository = new CommentRepository();
            _contactRepository = new ContactRepository();
        }

        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contact
        public ActionResult List(int page = 1, ModeType mode = ModeType.List, string searchText = null)
        {
            // configure paging
            var pageIndex = page;
            int perPage = 10;
            int skip = (pageIndex - 1) * perPage;

            var tupleContacts = new Tuple<int, ICollection<Contact>>(0, new List<Contact>());
            try
            {
                // get data
                if (mode == ModeType.List)
                    tupleContacts = _contactRepository.GetAll(skip, perPage);
                else // search by name
                    tupleContacts = _contactRepository.GetByName(searchText, skip, perPage);
            }
            catch (Exception ex)
            {
                // show error to view
                ModelState.AddModelError("error", ex.InnerException?.Message ?? ex.Message);
                // save notification message temporaly
                TempData["Error"] = ex.InnerException?.Message ?? ex.Message;
            }
            // get total rows exists in database
            var totalContacts = tupleContacts.Item1;
            var totalPage = Math.Ceiling((double)totalContacts / (double)perPage);

            var contacts = tupleContacts.Item2;
            ViewBag.TotalPage = totalPage;
            ViewBag.TotalResults = tupleContacts.Item1;
            // specify if we are in 'Search mode' or 'List mode'
            ViewBag.Mode = mode;
            // back text to view
            ViewBag.SearchText = searchText;


            return View(contacts);
        }

        // POST: Contact/Search
        public ActionResult Search(string search, int page = 1)
        {
            // if user press Enter keyword, without write any text in the search input
            if (string.IsNullOrEmpty(search))
            {
                ModelState.AddModelError("error", "Veuillez renseigner l'information a rechercher !");
                // save notification message temporaly
                TempData["Error"] = "Veuillez renseigner l'information a rechercher !";
                return RedirectToAction("List");
            }
            return RedirectToAction("List", new { page = page, searchText = search, mode = ModeType.Search });
        }


        // GET: Contact/Details/5
        public ActionResult Details(long id)
        {
            try
            {
                var foundContact = _contactRepository.Get(id);
                if (foundContact == null)
                {
                    // back to list with error msg
                    ModelState.AddModelError("error", "Contact introuvable !");
                    // save notification message temporaly
                    TempData["Error"] = "Contact introuvable !";
                    return RedirectToAction("List");
                }
                // get all contact comment's
                var comments = _commentRepository.GetAllByContact(foundContact.Id.Value);
                // use to show all comments inside the view
                ViewBag.Comments = comments.Item2.Select(x => x.Content);

                return View(foundContact);
            }
            catch (Exception ex)
            {
                // show error to view
                ModelState.AddModelError("error", ex.InnerException?.Message ?? ex.Message);
                // save notification message temporaly
                TempData["Error"] = ex.InnerException?.Message ?? ex.Message;
                return RedirectToAction("List");
            }
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contact contact)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //extract all form cmments
                    var commentVals = Request.Form.GetValues("comment");
                    // constuct comment entity model list: (the contactId value will be replaced
                    // in all comments after the contact is created)
                    List<Comment> comments = commentVals?
                        .Select(x => new Comment(x, 0)).ToList() ?? new List<Comment>();

                    // set contacts comments
                    contact.Comments = comments;

                    _contactRepository.Create(contact);

                    // save notification message temporaly
                    TempData["Success"] = "Le contact a été ajouté avec success !";
                    return RedirectToAction("List");
                }
                catch(Exception ex)
                {
                    // show error to view
                    ModelState.AddModelError("error", ex.InnerException?.Message ?? ex.Message);
                    // save notification message temporaly
                    TempData["Error"] = ex.InnerException?.Message ?? ex.Message;
                    return View();
                }
            }
            return View();
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(long id)
        {
            try
            {
                var foundContact = _contactRepository.Get(id);
                if (foundContact == null)
                {
                    // back to list with error msg
                    ModelState.AddModelError("error", "Contact introuvable !");
                    // save notification message temporaly
                    TempData["Error"] = "Contact introuvable !";
                    return RedirectToAction("List");
                }
                // get all contact comment's
                var comments = _commentRepository.GetAllByContact(foundContact.Id.Value);

                // use to show all comments inside the view
                ViewBag.Comments = comments.Item2.Select(x => x.Content);

                return View(foundContact);
            }
            catch (Exception ex)
            {
                // show error to view
                ModelState.AddModelError("error", ex.InnerException?.Message ?? ex.Message);
                // save notification message temporaly
                TempData["Error"] = ex.InnerException?.Message ?? ex.Message;
                return RedirectToAction("List");
            }
        }

        // POST: Contact/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long id, Contact contact)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //extract all form cmments
                    var commentVals = Request.Form.GetValues("comment");
                    // constuct comment entity model list
                    List<Comment> comments = commentVals?
                        .Select(x => new Comment(x, id)).ToList() ?? new List<Comment>();

                    // update contacts comments
                    contact.Comments = comments;

                    _contactRepository.Update(id, contact);

                    // save notification message temporaly
                    TempData["Success"] = "Le contact a été mis a jour !";
                    return RedirectToAction("List");
                }
                catch (Exception ex)
                {
                    // reload model data
                    var foundContact = _contactRepository.Get(id);
                    if (foundContact == null)
                    {
                        // back to list with error msg
                        ModelState.AddModelError("error", "Contact introuvable !");
                        // save notification message temporaly
                        TempData["Error"] = "Contact introuvable !";
                        return RedirectToAction("List");
                    }
                    // get all contact comment's
                    var comments = _commentRepository.GetAllByContact(foundContact.Id.Value);

                    // use to show all comments inside the view
                    ViewBag.Comments = comments.Item2.Select(x => x.Content);

                    // show error to view
                    ModelState.AddModelError("error", ex.InnerException?.Message ?? ex.Message);
                    // save notification message temporaly
                    TempData["Error"] = ex.InnerException?.Message ?? ex.Message;
                    return View(foundContact);
                }
            }

            // reload model data
            var foundContact_ = _contactRepository.Get(id);
            if (foundContact_ == null)
            {
                // back to list with error msg
                ModelState.AddModelError("error", "Contact introuvable !");
                // save notification message temporaly
                TempData["Error"] = "Contact introuvable !";
                return RedirectToAction("List");
            }
            // get all contact comment's

Views/Shared/DeleteModal.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteModal</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/Shared/_DeleteModal.cshtml
@section Css
{
    <link href="~/Content/mdb.min.css" rel="stylesheet" />
}

<!-- Modal -->
@using (Html.BeginForm("","", FormMethod.Post, new {id = "delete-form"}))
{
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="text-danger">Opération irréversible</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        Voulez-vous vraiment supprimer ce contact ? <br />
                        <strong id="contact-name" class=" text-muted"></strong>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn bg-light mb-0" data-bs-dismiss="modal">Annuler</button>
                    <button id="btn-delete" type="submit" class="btn bg-gradient-primary mb-0">Oui</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
{
    <script src="~/Scripts/mdb.min.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title | Contact Management Web Site</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

    <!-- Nucleo Icons -->
    <link href="~/Content/nucleo-icons.css" rel="stylesheet" />
    <link href="~/Content/nucleo-svg.css" rel="stylesheet" />

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <!-- CSS Files -->
    <link id="pagestyle" href="~/Content/material-kit.css?v=3.0.4" rel="stylesheet" />

    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

    <!-- Google Fonts Roboto -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />

    <!--  toast -->
    <link href="~/Content/jquery.toast.css" rel="stylesheet" />

    @RenderSection("css", required: false)
</head>
<body class="forms-sections">
    <div class="container position-sticky z-index-sticky top-0">
        <div class="row">
            <div class="col-12">
                <!--   Start Navbar  -->
                <nav class="navbar navbar-dark navbar-expand-lg  blur border-radius-xl top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
                    <div class="container-fluid px-0">
                        @Html.ActionLink("GEST ¤ CONTACT", "Index", "Home", new { }, new { @class = "navbar-brand font-weight-bolder ms-sm-3", @rel = "tooltip" })
                        <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon mt-2">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </span>
                        </button>
                        <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                            <ul class="navbar-nav navbar-nav-hover ms-auto">
                                <li class="nav-item dropdown dropdown-hover mx-2">
                                    @Html.ActionLink("Acceuil", "Index", "Home", new { }, new { @class = "nav-link ps-2 d-flex cursor-pointer align-items-center" })
                                </li>

                                <li class="nav-item dropdown dropdown-hover mx-2">
                                    @Html.ActionLink("Mes contacts", "List", "Contact", new { }, new { @class = "nav-link ps-2 d-flex cursor-pointer align-items-center" })
                                </li>

                                <li class="nav-item dropdown dropdown-hover mx-2">
                                    @Html.ActionLink("Ajouter", "Create", "Contact", new { }, new { @class = "nav-link ps-2 d-flex cursor-pointer align-items-center" })
                                </li>

                                <li class="nav-item dropdown dropdown-hover mx-2">
                                    @Html.ActionLink("Importer des contacts", "Import", "Contact", new { }, new { @class = "nav-link ps-2 d-flex cursor-pointer align-items-center" })
                                </li>


                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- End Navbar -->
            </div>
        </div>
    </div>

    @RenderBody()

    <footer class="footer py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-4 mx-auto text-center">
                    <a href="javascript:;" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
                        Mes contacts
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
                        Règle
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
                        Aide &amp; Support
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
                        Importation
                    </a>
                </div>
                <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
                    <a href="javascript:;" class="text-secondary me-xl-4 me-4">
                        <span class="text-lg fab fa-dribbble" aria-hidden="true"></span>
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-4 me-4">
                        <span class="text-lg fab fa-twitter" aria-hidden="true"></span>
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-4 me-4">
                        <span class="text-lg fab fa-instagram" aria-hidden="true"></span>
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-4 me-4">
                        <span class="text-lg fab fa-pinterest" aria-hidden="true"></span>
                    </a>
                    <a href="javascript:;" class="text-secondary me-xl-4 me-4">
                        <span class="text-lg fab fa-github" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-8 mx-auto text-center mt-1">
                    <p class="mb-0 text-secondary">
                        Tous droit reservé. Copyright ©
                        <script>document.write(new Date().getFullYear())</script> <strong>GEST ¤ CONTACT</strong>.
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <p class="d-none" id="successToast">@TempData["Success"]</p>
    <p class="d-none" id="errorToast">@TempData["Error"]</p>

    <script src="~/Scripts/choices.min.js"></script>
    <script src="~/Scripts/countup.min.js"></script>
    <script src="~/Scripts/highlight.min.js"></script>
    <script src="~/Scripts/material-kit.min.js?v=3.0.4"></script>
    <script src="~/Scripts/parallax.min.js"></script>
    <script src="~/Scripts/perfect-scrollbar.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/prism.min.js"></script>
    <script src="~/Scripts/rellax.min.js"></script>
    <script src="~/Scripts/tilt.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.toast.js"></script>

    <script>
        // make an toast to notify request status
        if ($("#successToast").text() != "") { 
            $.toast({
                position: 'top-right',
                heading: 'Success | Gest ¤ Contact',
                text: $("#successToast").text(),
                icon: 'success',
                showHideTransition: 'plain',
                hideAfter: 7000,
            });
        }
        if ($("#errorToast").text() != "") {
            $.toast({
                position: 'top-right',
                heading: 'Error | Gest ¤ Contact',
                text: $("#errorToast").text(),
                icon: 'error',
                showHideTransition: 'plain',
                hideAfter: 7000,
            });
        }
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>